# Generated by Django 5.2.1 on 2025-05-31 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0004_perfilusuario_delete_cadastrouser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='artista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='aplicativo.cadastrotatuador'),
        ),
    ]
