# Generated by Django 5.2.1 on 2025-06-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0006_remove_mensagem_artista_remove_mensagem_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrotatuador',
            name='bio',
            field=models.TextField(blank=True, help_text='Uma breve descrição sobre o artista e seu estilo.', null=True, verbose_name='Bio do artista'),
        ),
        migrations.AddField(
            model_name='cadastrotatuador',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil do artista.', null=True, upload_to='artistas_fotos/', verbose_name='Foto de Perfil'),
        ),
    ]
