# Generated by Django 4.2.23 on 2025-06-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0007_cadastrotatuador_bio_cadastrotatuador_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='imagem_proposta',
            field=models.ImageField(blank=True, null=True, upload_to='propostas/'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
