# Generated by Django 5.2.1 on 2025-05-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro_tatuador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=50, verbose_name='Seu primeiro nome')),
                ('sobre_nome', models.CharField(max_length=50, verbose_name='Seu sobrenome')),
                ('email', models.EmailField(max_length=250, verbose_name='Seu email')),
                ('nome_estudio', models.CharField(max_length=50, verbose_name='Nome do seu estúdio')),
            ],
        ),
        migrations.CreateModel(
            name='cadastro_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=50, verbose_name='Seu primeiro nome')),
                ('sobre_nome', models.CharField(max_length=50, verbose_name='Seu sobrenome')),
                ('email', models.EmailField(max_length=250, verbose_name='Seu email')),
            ],
        ),
    ]
