# Generated by Django 5.2.1 on 2025-05-19 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cadastro_tatuador',
            new_name='CadastroTatuador',
        ),
        migrations.RenameModel(
            old_name='cadastro_user',
            new_name='CadastroUser',
        ),
    ]
